---
title: "Central American Migration"
author: "Mario Moreno"
date: "1/27/2019"
output:
  pdf_document: default
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r packsandlibs, include=FALSE}
install.packages('ggplot2')
install.packages('tidyverse')
install.packages('gghighlight')
install.packages('ggalluvial')
install.packages('rmarkdown')

library(ggalluvial)
library(ggplot2)
library(ggrepel)
library(gghighlight)
library(gtools)
library(tidyverse)
library(dplyr)
```
```{r dataloads, include=FALSE}
# READING IN FOR BAR, LINE, AND BUBBLE GRAPHS
elsLAPOP <- read.csv('Data/elsLAPOP.csv')
guateLAPOP <- read.csv('Data/guateLAPOP.csv')
hondLAPOP <- read.csv('Data/hondLAPOP.csv', encoding = 'latin1')
sec <- read.csv('Data/security.csv')

elsLAPOP$pais[elsLAPOP$pais==3] <- "El Salvador"
guateLAPOP$pais[guateLAPOP$pais==2] <- "Guatemala"
hondLAPOP$pais[hondLAPOP$pais==4] <- "Honduras"

cols_to_keep <- intersect(colnames(elsLAPOP), colnames(guateLAPOP))
g <- guateLAPOP[, cols_to_keep, drop=FALSE]
e <- elsLAPOP[, cols_to_keep, drop=FALSE]
bind <- smartbind(g, e)
cols_to_keep <- intersect(colnames(bind), colnames(hondLAPOP))
h <- hondLAPOP[, cols_to_keep, drop=FALSE]
b <- bind[, cols_to_keep, drop=FALSE]
LAPOP <- smartbind(h, b)

rm(cols_to_keep, g, e, h, b, bind)

## READING FOR ALLUVIAL GRAPH
hmex <- read.csv('Data/honddev2017mex.csv')
hmex$pais <- 'Honduras'
hmex$deported <- 'Mexico'

husa <- read.csv('Data/honddev2017usa.csv')
husa$pais <- 'Honduras'
husa$deported <- 'USA'

cols_to_keep_mex <- c('pais', 'deported', 'p15', 'p22_1e', 'p22_1l', 'p22_2e', 'p22_2l', 'p24l', 'p34l')
cols_to_keep_usa <- c('pais', 'deported', 'p14_1', 'p19_1e', 'p19_1l', 'p19_2e', 'p19_2l', 'p20l', 'p26')

husa1 <- husa[cols_to_keep_usa]
hmex1 <- hmex[cols_to_keep_mex]

colnames(husa1)[colnames(husa1)=="p14_1"] <- "p15"
colnames(husa1)[colnames(husa1)=="p19_1e"] <- "p22_1e"
colnames(husa1)[colnames(husa1)=="p19_1l"] <- "p22_1l"
colnames(husa1)[colnames(husa1)=="p19_2e"] <- "p22_2e"
colnames(husa1)[colnames(husa1)=="p19_2l"] <- "p22_2l"
colnames(husa1)[colnames(husa1)=="p20l"] <- "p24l"

alluvial <- dplyr::bind_rows(husa1, hmex1)
alluvial[is.na(alluvial)] <- 0
rm(hmex, husa, hmex1, husa1, cols_to_keep_usa, cols_to_keep_mex)

## READING IN FOR SLOPE GRAPH
path <- "Data/"
files <- list.files(path=path, pattern="*usa.csv")
for(file in files)
{
  perpos <- which(strsplit(file, "")[[1]]==".")
  assign(
    gsub(" ","",substr(file, 1, perpos-1)), 
    read.csv(paste(path,file,sep="")))
}

# Add country identifiers
elsdev2014usa$pais <- 'El Salvadorean migrants'
elsdev2015usa$pais <- 'El Salvadorean migrants'
elsdev2016usa$pais <- 'El Salvadorean migrants'
elsdev2017usa$pais <- 'El Salvadorean migrants'

honddev2014usa$pais <- 'Honduran migrants'
honddev2015usa$pais <- 'Honduran migrants'
honddev2016usa$pais <- 'Honduran migrants'
honddev2017usa$pais <- 'Honduran migrants'

guatedev2014usa$pais <- 'Guatemalan migrants'
guatedev2015usa$pais <- 'Guatemalan migrants'
guatedev2016usa$pais <- 'Guatemalan migrants'
guatedev2017usa$pais <- 'Guatemalan migrants'

# subset dataframes
e2014 <- elsdev2014usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
e2015 <- elsdev2015usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
e2016 <- elsdev2016usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
e2017 <- elsdev2017usa[c('year', 'pais', 'p17_1c', 'p17_1u')]

h2014 <- honddev2014usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
h2015 <- honddev2015usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
h2016 <- honddev2016usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
h2017 <- honddev2017usa[c('year', 'pais', 'p17_1c', 'p17_1u')]

g2014 <- guatedev2014usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
g2015 <- guatedev2015usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
g2016 <- guatedev2016usa[c('year', 'pais', 'p17_1c', 'p17_1u')]
g2017 <- guatedev2017usa[c('year', 'pais', 'p17_1c', 'p17_1u')]

rm(elsdev2014usa, elsdev2015usa, elsdev2016usa, elsdev2017usa, honddev2014usa, honddev2015usa, honddev2016usa, honddev2017usa, guatedev2014usa, guatedev2015usa, guatedev2016usa, guatedev2017usa)

# bind them 
slopegraph <- do.call("rbind", list(e2014, e2015, e2016, e2017, h2014, h2015, h2016, h2017, g2014, g2015, g2016, g2017))
rm(e2014, e2015, e2016, e2017, h2014, h2015, h2016, h2017, g2014, g2015, g2016, g2017)
```

# The Changing Dynamics of Central American Migration

```{r refugees}
# Calulcate the percent of people who've considered emigration over time

new <- LAPOP %>%
  select(year, pais, q14) %>%
  group_by(year, pais) %>%
  add_tally() %>%
  add_count(q14)

new$perc <- (new$nn / new$n) * 100

f <- new %>%
  select(year, pais, perc, q14) %>%
  group_by(year, pais) %>%
  arrange(q14) %>%    
  slice(1)

# Plot
 
plot <- ggplot(f,aes(x = year, y = perc, color= pais)) + 
  geom_line(stat='identity', width=1) 

plot + labs(title = "More people are planning to emigrate \n from Honduras than ever before",
            subtitle = "Across Central America, plans to emigrate \n have increased substantially since 2010",
            caption = "Source: LAPOP data, 2010-2017", 
            x = "Years", y = "Percent Planning to Emigrate",
            fill='Country') + theme(
              plot.title = element_text(color="black", size=14, face="bold", hjust=0.5),
              plot.subtitle = element_text(color="black", size=12, face="italic", hjust=0.5),
              axis.title.x = element_text(color="black", size=10),
              axis.title.y = element_text(color="black", size=10),
              plot.caption = element_text(color="black", size=8, face="italic"))

rm(new, f, plot)
```

## What's driving the migration (violence or economic opportunity?)
```{r drivers}
## This graph will show perceptions in violence and economic opportunity
## relative to answers on willingness to emigrate in the next 3 years for 2017

hond2017 <- subset(hondLAPOP, year==2016)

# Calculate the percent of people in each province who said they felt
# "Very unsafe" in the community

unsafe <- hond2017 %>%
  select(year, prov, aoj11) %>%
  group_by(year, prov) %>%
  add_tally() %>%
  add_count(aoj11)

# Calculate the percent of people in each province who said their economic
# situation has worsnened in the last 12 months

econ <- hond2017 %>%
  select(year, prov, idio2) %>%
  group_by(year, prov) %>%
  add_tally() %>%
  add_count(idio2)

# Calculate the percent of people in each province who want to emigrate
# in the next 3 years

emigrate <- hond2017 %>%
  select(year, prov, q14) %>%
  group_by(year, prov) %>%
  add_tally() %>%
  add_count(q14)

# Group by and replace those provinces that don't have those values with zero
# percent

emigrate$perc_emigrate <- (emigrate$nn / emigrate$n) * 100
unsafe$perc_aoj11 <- (unsafe$nn / unsafe$n) * 100
econ$perc_idio2 <- (econ$nn / econ$n) * 100

emigrate.na <- na.omit(emigrate)
unsafe.na <- na.omit(unsafe)
econ.na <- na.omit(econ)

to_plot_emigrate <- emigrate.na %>%
  select(year, prov, perc_emigrate, q14) %>%
  group_by(year, prov) %>%
  arrange(q14) %>%
  slice(1)

to_plot_econ <- econ.na %>%
  select(year, prov, perc_idio2, idio2) %>%
  group_by(year, prov) %>%
  arrange(desc(idio2)) %>%    
  slice(1)

to_plot_unsafe <- unsafe.na %>%
  select(year, prov, perc_aoj11, aoj11) %>%
  group_by(year, prov) %>%
  arrange(desc(aoj11)) %>%    
  slice(1)

to_plot_final <- merge(to_plot_econ, to_plot_unsafe, by = c("year", "prov"))
to_plot_final <- merge(to_plot_final, to_plot_emigrate, by = c("year", "prov"))
to_plot_f <- to_plot_final %>% mutate(perc_aoj11 = ifelse(aoj11 != 4, 0, perc_aoj11))
to_plot_ff <- to_plot_f %>% mutate(perc_idio2 = ifelse(idio2 != 3, 0, perc_idio2))

rm(to_plot_final, to_plot_f, to_plot_econ, to_plot_unsafe, unsafe, econ, unsafe.na, econ.na)                                   

# Plot


plot <- ggplot(to_plot_ff, 
               aes(y = perc_aoj11, x = perc_idio2, color = perc_emigrate)) + geom_point( alpha=0.2) +          
  geom_text_repel(aes(label=prov)) + scale_color_distiller(name = '% planning to emigrate', palette='RdPu', trans='reverse') + 
  scale_y_continuous(limits = c(0, 60)) + expand_limits(x=0)

plot + labs(title = "In Honduran provinces with largest percentage of people \n planning to emigrate, economic concerns prevail",
            subtitle = "Economics might be playing a larger push role than violence",
            caption = "Source: LAPOP Honduras data 2017", 
            x = "% who feel economic prospects have worsened", y = "% who feel very unsafe from crime",
            fill='Province') + theme(
              plot.title = element_text(color="black", size=14, face="bold", hjust=0.5),
              plot.subtitle = element_text(color="black", size=12, face="italic", hjust=0.5),
              axis.title.x = element_text(color="black", size=10),
              axis.title.y = element_text(color="black", size=10),
              plot.caption = element_text(color="black", size=8, face="italic"),
              legend.justification = c(0.75, 0.75), 
              legend.position = c(0.25,.75), 
              legend.title = element_text(colour="black", size=12, 
                                          face="bold"))

```

## How has the cost changed over time?
```{r cost}
tograph <- slopegraph %>%
  group_by(year, pais) %>%
  filter(p17_1c >0, p17_1u == 3) %>%
  summarize(mean_spent = mean(p17_1c)) %>%
  mutate_if(is.numeric, round, 0)

rm(e2014, e2015, e2016, e2017, h2014, h2015, h2016, h2017, g2014, g2015, g2016, g2017)

# Slope graph

 
ggplot(data = tograph, aes(x = year, y = mean_spent, group = pais)) +
  geom_line(aes(color = pais, alpha = 1), size = 1) + 
  geom_text_repel(data = tograph %>% filter(year == 2017), 
                  aes(label = pais) , 
                  hjust = "right", 
                  fontface = "bold", 
                  size = 3.5, 
                  nudge_x = -0.25, 
                  direction = "y") + 
  geom_label(aes(label = paste0("$", mean_spent)), 
             size = 3, 
             label.padding = unit(0.05, "lines"), 
             label.size = 0.0) +
  # move the x axis labels up top
  #scale_x_discrete(position = "top") +
  theme_bw() +
  # Format tweaks
  # Remove the legend
  theme(legend.position = "none") +
  # Remove the panel border
  theme(panel.border     = element_blank()) +
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()) +
  theme(axis.text.y      = element_blank()) +
  theme(panel.grid.major.y = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()) +
  theme(panel.grid.major.x = element_blank()) +
  theme(axis.text.x.top      = element_text(size=12)) +
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()) +
  # Format title & subtitle
  theme(plot.title       = element_text(size=14, face = "bold", hjust = 0.5)) +
  theme(plot.subtitle    = element_text(hjust = 0.5)) +
  #  Labelling as desired
  labs(
    title = "Price paid by Honduran migrants to the coyotes successfully \n trafficking them through Mexico has increased since 2014",
    subtitle = "Guatemalan migrants have experienced similar increases, \n but Salvadorean migrants have paid less for a successful trip",
    caption = "Source: EMIF Sur (2014-2017)"
  )
```

## What's the route that Central American migrants take northward?
```{r routes}

drop1 <- alluvial %>% filter(p15 >= 0, p22_1l >= 0, p22_2l >= 0, p26 >= 0, p24l >= 0)
clean <- drop1 %>% filter(p15 < 2000000, p22_1l < 900000000, p22_2l < 900000000, p26 < 300000000, p24l < 9000000000)
rm(drop1)

alluvialnodeshond <- rename(count(clean, deported, p15, p22_1l, p22_2l, p24l, p26, p34l), Freq = n)
touse <- alluvialnodeshond %>% filter(Freq>2)

## Make names for it

touse$p15[touse$p15 == 1217001] <- 'Tecun Uman'
touse$p15[touse$p15 == 1705099] <- 'Naranjo'
touse$p15[touse$p15 == 1705016] <- 'El Ceibo'
touse$p15[touse$p15 == 1705015] <- 'Bethel'
touse$p15[touse$p15 == 1312047] <- 'La Mesilla'

touse$p22_1l[touse$p22_1l == 301930001] <- 'Veracruz, VER'
touse$p22_1l[touse$p22_1l == 300390001] <- 'Coatzacoalcos, VER'
touse$p22_1l[touse$p22_1l == 270170001] <- 'Tenosique de Pino Suarez, TAB'
touse$p22_1l[touse$p22_1l == 270040001] <- 'Villahermosa, TAB'
touse$p22_1l[touse$p22_1l == 240280001] <- 'San Luis Potosi, SLP'
touse$p22_1l[touse$p22_1l == 190390001] <- 'Monterrey, NL'
touse$p22_1l[touse$p22_1l == 70650001] <- 'Palenque, CHIS'
touse$p22_1l[touse$p22_1l == 70270001] <- 'Chiapa de Corzo, CHIS'


touse$p24l[touse$p24l == 300030001] <- 'Acayucan, VER'
touse$p24l[touse$p24l == 280320001] <- 'Reynosa, TAMPS'
touse$p24l[touse$p24l == 280270001] <- 'N. Laredo, TAMPS'
touse$p24l[touse$p24l == 270020001] <- 'Cardenas, TAB'
touse$p24l[touse$p24l == 301930001] <- 'Veracruz, VER'
touse$p24l[touse$p24l == 300390001] <- 'Coatzacoalcos, VER'
touse$p24l[touse$p24l == 270170001] <- 'Tenosique de Pino Suarez, TAB'
touse$p24l[touse$p24l == 270040001] <- 'Villahermosa, TAB'
touse$p24l[touse$p24l == 70650001] <- 'Palenque, CHIS'

touse$p34l[touse$p34l == 0] <- 'Avoided Deportation'
touse$p34l[touse$p34l == 300030001] <- 'Acayucan, VER'
touse$p34l[touse$p34l == 270020001] <- 'Cardenas, TAB'
touse$p34l[touse$p34l == 301930001] <- 'Veracruz, VER'
touse$p34l[touse$p34l == 300390001] <- 'Coatzacoalcos, VER'
touse$p34l[touse$p34l == 270170001] <- 'Tenosique de Pino Suarez, TAB'
touse$p34l[touse$p34l == 70650001] <- 'Palenque, CHIS'
touse$p34l[touse$p34l == 270040001] <- 'Villahermosa, TAB'


touse$p26[touse$p26 == 0] <- 'Deported Prior'
touse$p26[touse$p26 == 280320001] <- 'Reynosa, TAMPS'
touse$p26[touse$p26 == 280270001] <- 'N. Laredo, TAMPS'

ggplot(touse,
       aes(y = Freq,
           axis1 = p15, axis2 = p22_1l, axis3 = p24l, axis4 = p26)) +
  geom_alluvium(aes(fill = deported),
                width = 0.1, knot.pos = 0, reverse = FALSE) +
  guides(fill = FALSE) +
  geom_stratum(width = 1/10, reverse = FALSE) +
  geom_text(stat = "stratum", label.strata = TRUE, reverse = FALSE) +
  scale_x_continuous(breaks = 1:4, labels = c("Mexican Port of Entry", "Mexican City Visited", "Mexican City Where Spent Most Time" ,"US Port of Entry")) +
  labs(
    title = "As they journey northward, Honduran migrants who get \n deported in Mexico (red) get stuck in cities that border the Gulf of Mexico",
    subtitle = "Most migrants who make it to the US (blue) enter through Reynosa",
    caption = "Source: EMIF Sur (2014-2017)") + theme(
      plot.title = element_text(color="black", size=12, face="bold", hjust=0.5),
      plot.subtitle = element_text(color="black", size=10, face="italic", hjust=0.5),
      axis.title.x = element_text(color="black", size=8),
      axis.title.y = element_text(color="black", size=8),
      plot.caption = element_text(color="black", size=6, face="italic"))

```

## What is the US investing in Honduras to make it better?

```{r usaid, echo=FALSE}
hond_sec <- subset(sec, country_name == 'Honduras')
hond_sec$dac_sector_name[is.na(hond_sec$dac_sector_name)] <- "Conflict, Peace, and Security"

to_plot_sec <- hond_sec %>%
  select(fiscal_year, dac_sector_name, constant_amount) %>%
  group_by(fiscal_year, dac_sector_name) %>%
  tally(constant_amount)

plot <- gghighlight_line(to_plot_sec, aes(fiscal_year, n, colour = dac_sector_name), predicate = max(n),
                 max_highlight = 3)

plot + scale_y_continuous(name = "Amount (in 10,000,000)", labels = c(0, 2, 
                                                                           4, 6, 8)) + 
  labs(title = "US Investments in Honduras have focused on civil society \n and government",
             subtitle = "There's notable increases since 2015, the year \n after the unaccompanied minors crisis",
             caption = "Source: USAID Foreign Aid Explorer and Security Assistance Monitor data, 2010-2017", 
             x = "Fiscal Year",
             fill='Province') + theme(
               plot.title = element_text(color="black", size=14, face="bold", hjust = 0.5),
               plot.subtitle = element_text(color="black", size=12, face="italic", hjust =0.5),
               axis.title.x = element_text(color="black", size=10),
               axis.title.y = element_text(color="black", size=10),
               plot.caption = element_text(color="black", size=8, face="italic"))
```

